flowchart TD
    A([Entry]) --> B[Def interval (parameter)]
    B --> C[Def thisStart, thisEnd]
    C --> D{P-use: interval == null}

    D -- True --> E[Def now]
    E --> F[P-use: thisStart < now]
    F --> G[P-use: now < thisEnd]
    G --> H[Return boolean]

    D -- False --> I[Def otherStart, otherEnd]
    I --> J[P-use: thisStart < otherEnd]
    J --> K[P-use: otherStart < thisEnd]
    K --> L[Return boolean]

    H --> M([Exit])
    L --> M
